# Generated by Django 5.2.1 on 2025-05-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genNombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelCodigo', models.CharField(max_length=10, unique=True)),
                ('pelTitulo', models.CharField(max_length=100)),
                ('pelProtagonista', models.CharField(max_length=100)),
                ('pelDuracion', models.IntegerField()),
                ('pelResumen', models.TextField(max_length=500)),
                ('pelFoto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('pelGenero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPeliculas.genero')),
            ],
        ),
    ]
